import { Equipment, Booking, MaintenanceReminder, DisputeCase, FraudFlag } from "./types";

export const initialEquipmentList: Equipment[] = [
  {
    id: "eq-01",
    name: "Tata Hitachi ZAXIS 220LC Hydraulic Excavator",
    category: "earthmoving",
    brand: "Tata Hitachi",
    modelNumber: "ZAXIS 220LC-GI Series",
    year: 2023,
    tonnage: 22,
    horsepower: 170,
    fuelType: "Diesel",
    hourlyRate: 3200,
    dailyRate: 26000,
    monthlyRate: 650000,
    mobilizationBaseRatePerKm: 65,
    operatorIncluded: true,
    operatorDailyCharge: 1500,
    fuelIncluded: false,
    location: {
      lat: 12.9716,
      lng: 77.5946,
      city: "Bangalore Urban",
      district: "Whitefield & Electronic City Corridor",
      state: "Karnataka",
      address: "Heavy Yard 14, Outer Ring Road, Mahadevapura, Bengaluru",
    },
    rating: 4.9,
    reviewCount: 42,
    verified: true,
    rcNumber: "KA-01-EX-9921",
    insuranceValidUntil: "2027-04-30",
    fitnessValidUntil: "2028-11-15",
    ownerId: "owner-101",
    ownerName: "Sri Manjunatha Earthmovers & Infra",
    ownerPhone: "+91 98450 12389",
    operatorName: "Manjunath Gowda (Certified Class 1 Pilot)",
    operatorPhone: "+91 94480 88219",
    available: true,
    blockedDates: ["2026-09-10", "2026-09-11"],
    attachmentsAvailable: ["Heavy Duty Rock Breaker (150mm chisel)", "1.2m³ Heavy Bucket", "Trenching Bucket (400mm)", "Hydraulic Grabber"],
    specs: {
      maxDiggingDepthM: 6.6,
      bucketCapacityCbm: 1.2,
      liftingCapacityTons: 6.5,
      boomLengthM: 5.68,
    },
    liveGps: {
      lat: 12.9822,
      lng: 77.6105,
      speedKmH: 34,
      fuelLevelPct: 82,
      engineHours: 1420.5,
      batteryVoltage: 24.6,
      engineRpm: 1750,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "High breakout force 22-ton crawler excavator equipped with Isuzu 6-cylinder engine and Japanese hydraulics. Best suited for granite basement excavation, highway cuts, and heavy drainage canal laying.",
  },
  {
    id: "eq-02",
    name: "JCB 3DX Plus EcoXcellence Backhoe Loader",
    category: "earthmoving",
    brand: "JCB India",
    modelNumber: "3DX Plus 4WD",
    year: 2024,
    tonnage: 7.8,
    horsepower: 76,
    fuelType: "Diesel",
    hourlyRate: 1600,
    dailyRate: 13500,
    monthlyRate: 340000,
    mobilizationBaseRatePerKm: 45,
    operatorIncluded: true,
    operatorDailyCharge: 1200,
    fuelIncluded: false,
    location: {
      lat: 12.5218,
      lng: 76.8951,
      city: "Mandya",
      district: "Mandya & Maddur Region",
      state: "Karnataka",
      address: "Near Sugar Factory Road, Mandya Central",
    },
    rating: 4.8,
    reviewCount: 68,
    verified: true,
    rcNumber: "KA-11-JCB-4412",
    insuranceValidUntil: "2027-08-20",
    fitnessValidUntil: "2029-02-10",
    ownerId: "owner-102",
    ownerName: "Cauvery Farm & Agro Logistics",
    ownerPhone: "+91 98860 44910",
    operatorName: "Shivanna K. (12 Yrs Experience)",
    operatorPhone: "+91 97410 33812",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["6-in-1 Multi-purpose Front Shovel", "Rock Breaker Kit", "Ditch Cleaning Bucket", "Auger Drill (300mm)"],
    specs: {
      maxDiggingDepthM: 4.77,
      bucketCapacityCbm: 0.3,
      liftingCapacityTons: 1.8,
    },
    liveGps: {
      lat: 12.534,
      lng: 76.912,
      speedKmH: 0,
      fuelLevelPct: 75,
      engineHours: 890.2,
      batteryVoltage: 12.8,
      engineRpm: 800,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "1 min ago",
    },
    images: [
      "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "India's most trusted backhoe loader with EcoMAX turbocharged engine and LiveLink GPS telemetry. Perfect for farm leveling, canal trenching, rural road formation, and construction debris handling.",
  },
  {
    id: "eq-03",
    name: "John Deere W70 Multi-Crop Grain Combine Harvester",
    category: "agricultural",
    brand: "John Deere",
    modelNumber: "W70 SynchroSmart",
    year: 2023,
    tonnage: 8.5,
    horsepower: 100,
    fuelType: "Diesel",
    hourlyRate: 2400,
    dailyRate: 19000,
    monthlyRate: 480000,
    mobilizationBaseRatePerKm: 55,
    operatorIncluded: true,
    operatorDailyCharge: 1800,
    fuelIncluded: true,
    location: {
      lat: 12.2958,
      lng: 76.6394,
      city: "Mysore",
      district: "Mysuru & Nanjangud Agri Belt",
      state: "Karnataka",
      address: "APMC Yard Road, Bandipalya, Mysuru",
    },
    rating: 4.95,
    reviewCount: 38,
    verified: true,
    rcNumber: "KA-09-HR-1830",
    insuranceValidUntil: "2027-01-15",
    fitnessValidUntil: "2029-06-30",
    ownerId: "owner-103",
    ownerName: "Krishi Mitra Agro Services",
    ownerPhone: "+91 99001 77234",
    operatorName: "Raju Patil (Harvester Specialist)",
    operatorPhone: "+91 96112 55901",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Paddy Cutter Bar (3.6m)", "Wheat Header", "Maize Corn Header", "Straw Chopper"],
    specs: {
      grainTankCapacityL: 2100,
      cutterBarWidthM: 3.65,
    },
    liveGps: {
      lat: 12.312,
      lng: 76.658,
      speedKmH: 18,
      fuelLevelPct: 91,
      engineHours: 640.0,
      batteryVoltage: 12.7,
      engineRpm: 1900,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "Advanced multi-crop combine harvester with SynchroSmart floating cutter bar and high cleaning efficiency. Minimal grain loss (<1%) across paddy, wheat, soybean, and pulses.",
  },
  {
    id: "eq-04",
    name: "Mahindra Novo 755 DI 4WD Agri Tractor with Rotavator",
    category: "agricultural",
    brand: "Mahindra & Mahindra",
    modelNumber: "Novo 755 DI (74 HP)",
    year: 2024,
    tonnage: 3.2,
    horsepower: 74,
    fuelType: "Diesel",
    hourlyRate: 850,
    dailyRate: 5800,
    monthlyRate: 140000,
    mobilizationBaseRatePerKm: 30,
    operatorIncluded: true,
    operatorDailyCharge: 900,
    fuelIncluded: false,
    location: {
      lat: 13.3409,
      lng: 77.101,
      city: "Tumkur",
      district: "Tumakuru Rural & Sira",
      state: "Karnataka",
      address: "B.H. Road, Near Toll Plaza, Tumakuru",
    },
    rating: 4.85,
    reviewCount: 54,
    verified: true,
    rcNumber: "KA-06-TR-8819",
    insuranceValidUntil: "2027-10-12",
    fitnessValidUntil: "2030-01-01",
    ownerId: "owner-104",
    ownerName: "Basaveshwara Agro Machinery",
    ownerPhone: "+91 97312 90817",
    operatorName: "Praveen Kumar",
    operatorPhone: "+91 98800 11982",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Shaktiman Heavy Rotavator (8ft)", "Hydraulic Reversible MB Plough", "7-Tyne Cultivator", "Tipping Trolley (5 Ton)"],
    specs: {
      liftingCapacityTons: 2.6,
    },
    liveGps: {
      lat: 13.35,
      lng: 77.12,
      speedKmH: 0,
      fuelLevelPct: 68,
      engineHours: 410.8,
      batteryVoltage: 12.6,
      engineRpm: 0,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "5 mins ago",
    },
    images: [
      "https://images.unsplash.com/photo-1594771804886-a933bb2d609b?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "4-wheel drive high-torque tractor with Creeper speed gearbox and Digisense telematics. Designed for deep plowing, wet puddle farming, subsoiling, and heavy trolley haulage.",
  },
  {
    id: "eq-05",
    name: "Ajax Fiori Argo 4000 Self-Loading Concrete Mixer",
    category: "concrete",
    brand: "Ajax Engineering",
    modelNumber: "Argo 4000 (4.0 m³ Batch)",
    year: 2023,
    tonnage: 9.2,
    horsepower: 110,
    fuelType: "Diesel",
    hourlyRate: 2800,
    dailyRate: 22500,
    monthlyRate: 560000,
    mobilizationBaseRatePerKm: 60,
    operatorIncluded: true,
    operatorDailyCharge: 1500,
    fuelIncluded: false,
    location: {
      lat: 12.985,
      lng: 77.726,
      city: "Whitefield, Bengaluru",
      district: "Bangalore East & Hoskote",
      state: "Karnataka",
      address: "ITPL Main Road, Hoodi Industrial Estate",
    },
    rating: 4.92,
    reviewCount: 31,
    verified: true,
    rcNumber: "KA-53-MX-3011",
    insuranceValidUntil: "2027-03-22",
    fitnessValidUntil: "2029-05-18",
    ownerId: "owner-105",
    ownerName: "BuildTech ReadyMix Fleet",
    ownerPhone: "+91 99450 88200",
    operatorName: "Gopal Rao (Certified Batcher)",
    operatorPhone: "+91 94801 77622",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Electronic Weigh Batching System", "Additive Dispenser Pump", "180° Swivel Discharge Chute", "High Pressure Wash Jet"],
    specs: {
      drumCapacityCbm: 4.0,
    },
    liveGps: {
      lat: 12.991,
      lng: 77.734,
      speedKmH: 22,
      fuelLevelPct: 88,
      engineHours: 1120.4,
      batteryVoltage: 24.2,
      engineRpm: 1500,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "Self-loading concrete mobile batching plant producing on-site precision concrete up to 16 m³/hr. Built-in electronic load cells and printer for quality audit compliance.",
  },
  {
    id: "eq-06",
    name: "ACE 15XW Hydra Pick & Carry Mobile Crane 15T",
    category: "lifting",
    brand: "Action Construction Equipment",
    modelNumber: "15XW Heavy Duty",
    year: 2023,
    tonnage: 15,
    horsepower: 101,
    fuelType: "Diesel",
    hourlyRate: 2200,
    dailyRate: 17500,
    monthlyRate: 440000,
    mobilizationBaseRatePerKm: 50,
    operatorIncluded: true,
    operatorDailyCharge: 1400,
    fuelIncluded: false,
    location: {
      lat: 13.0285,
      lng: 77.5195,
      city: "Peenya Industrial Area, Bengaluru",
      district: "Bangalore North & Dasarahalli",
      state: "Karnataka",
      address: "Peenya 2nd Stage, Near Industrial Suburb Metro",
    },
    rating: 4.78,
    reviewCount: 45,
    verified: true,
    rcNumber: "KA-04-CR-7729",
    insuranceValidUntil: "2026-12-30",
    fitnessValidUntil: "2028-09-14",
    ownerId: "owner-106",
    ownerName: "Apex Heavy Cranes & Rigging",
    ownerPhone: "+91 98455 33211",
    operatorName: "Syed Imran (Third-Party Certified Rigger)",
    operatorPhone: "+91 97390 66541",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Fly Jib Extension (3m)", "Heavy Webbing Slings & D-Shackles", "Man Basket / Aerial Work Cage", "Spreader Beam 10T"],
    specs: {
      liftingCapacityTons: 15,
      boomLengthM: 13.5,
    },
    liveGps: {
      lat: 13.032,
      lng: 77.524,
      speedKmH: 0,
      fuelLevelPct: 70,
      engineHours: 975.0,
      batteryVoltage: 12.9,
      engineRpm: 750,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "2 mins ago",
    },
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "Versatile pick-and-carry 15-ton mobile hydraulic crane with 4-part slotted boom and safe load indicator (SLI). Ideal for industrial machinery erection, steel pre-fab loading, and metro precast handling.",
  },
  {
    id: "eq-07",
    name: "L&T 1190 Soil Compactor / Highway Road Roller",
    category: "roadwork",
    brand: "L&T Construction Equipment",
    modelNumber: "1190 Soil Compactor (11.5 Ton)",
    year: 2022,
    tonnage: 11.5,
    horsepower: 105,
    fuelType: "Diesel",
    hourlyRate: 2000,
    dailyRate: 16000,
    monthlyRate: 390000,
    mobilizationBaseRatePerKm: 55,
    operatorIncluded: true,
    operatorDailyCharge: 1200,
    fuelIncluded: false,
    location: {
      lat: 13.0033,
      lng: 76.1004,
      city: "Hassan",
      district: "Hassan & Sakleshpur Highway",
      state: "Karnataka",
      address: "B.M. Road, Industrial Growth Center, Hassan",
    },
    rating: 4.88,
    reviewCount: 29,
    verified: true,
    rcNumber: "KA-13-RR-5541",
    insuranceValidUntil: "2027-05-19",
    fitnessValidUntil: "2029-01-20",
    ownerId: "owner-107",
    ownerName: "Malnad Highway Infra",
    ownerPhone: "+91 94481 22900",
    operatorName: "Naveen Gowda",
    operatorPhone: "+91 96200 44819",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Padfoot Shell Kit (Sheepfoot Drum)", "GPS Pass Counter & Compaction Meter", "Water Sprinkler System"],
    specs: {
      compactionForceKn: 280,
    },
    liveGps: {
      lat: 13.012,
      lng: 76.115,
      speedKmH: 6,
      fuelLevelPct: 62,
      engineHours: 1840.1,
      batteryVoltage: 24.1,
      engineRpm: 1800,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "Heavy single drum vibratory soil compactor with dual amplitude and dual frequency. Optimal for embankment earthwork, sub-base gravel compaction, and industrial floor leveling.",
  },
  {
    id: "eq-08",
    name: "PRD Super 650 Truck-Mounted Borewell Drilling Rig",
    category: "drilling",
    brand: "PRD Rigs",
    modelNumber: "Super 650 High Pressure",
    year: 2023,
    tonnage: 18,
    horsepower: 240,
    fuelType: "Diesel",
    hourlyRate: 4500,
    dailyRate: 36000,
    monthlyRate: 850000,
    mobilizationBaseRatePerKm: 75,
    operatorIncluded: true,
    operatorDailyCharge: 2500,
    fuelIncluded: false,
    location: {
      lat: 13.1367,
      lng: 78.1291,
      city: "Kolar",
      district: "Kolar & Chikkaballapur",
      state: "Karnataka",
      address: "Bangalore-Tirupati NH 75, Kolar Industrial Area",
    },
    rating: 4.96,
    reviewCount: 37,
    verified: true,
    rcNumber: "KA-07-RG-9012",
    insuranceValidUntil: "2027-09-10",
    fitnessValidUntil: "2029-08-01",
    ownerId: "owner-108",
    ownerName: "Varuna Deep Ground Drilling",
    ownerPhone: "+91 99011 44520",
    operatorName: "Master Driller Annadurai",
    operatorPhone: "+91 98452 77019",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["1100 CFM / 350 PSI Screw Compressor", "6.5-inch DTH Button Bits (Rock)", "PCD Core Bits", "PVC Casing Inserter"],
    specs: {
      drillingDepthM: 650,
    },
    liveGps: {
      lat: 13.145,
      lng: 78.138,
      speedKmH: 0,
      fuelLevelPct: 80,
      engineHours: 1210.0,
      batteryVoltage: 24.4,
      engineRpm: 900,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "4 mins ago",
    },
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "High-pressure truck-mounted drilling rig capable of reaching 650 meters (2100 ft) in hard granite formations. Equipped with ELGI 1100 CFM screw compressor for fast penetration rate.",
  },
  {
    id: "eq-09",
    name: "Dronaid Hexacopter Agricultural Drone Sprayer (20L)",
    category: "agricultural",
    brand: "Dronaid Aero",
    modelNumber: "AgriHex 20L RTK",
    year: 2024,
    tonnage: 0.045,
    horsepower: 12,
    fuelType: "Electric",
    hourlyRate: 1500,
    dailyRate: 9500,
    monthlyRate: 220000,
    mobilizationBaseRatePerKm: 20,
    operatorIncluded: true,
    operatorDailyCharge: 1500,
    fuelIncluded: true,
    location: {
      lat: 12.5218,
      lng: 76.8951,
      city: "Mandya",
      district: "Mandya Sugar & Paddy Plains",
      state: "Karnataka",
      address: "Krishi Vigyan Kendra Road, Mandya",
    },
    rating: 4.9,
    reviewCount: 51,
    verified: true,
    rcNumber: "DGCA-UIN-882190",
    insuranceValidUntil: "2027-11-20",
    fitnessValidUntil: "2029-11-20",
    ownerId: "owner-109",
    ownerName: "Kisan Drone Flight Hub",
    ownerPhone: "+91 97400 66112",
    operatorName: "Anand R. (DGCA Certified Remote Pilot)",
    operatorPhone: "+91 99801 22340",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Centrifugal Atomizing Nozzle Kit", "Granule Spreader (Seeds/Fertilizer)", "Obstacle Avoidance Radar", "Terrain Following Radar"],
    specs: {
      grainTankCapacityL: 20,
    },
    liveGps: {
      lat: 12.528,
      lng: 76.902,
      speedKmH: 25,
      fuelLevelPct: 95,
      engineHours: 190.5,
      batteryVoltage: 48.2,
      engineRpm: 3800,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "DGCA Type-certified agricultural hexacopter drone with 20-liter payload. Covers 35 acres per day with uniform micro-droplet spraying, cutting pesticide use by 30% and water by 90%.",
  },
  {
    id: "eq-10",
    name: "BharatBenz 2828C Heavy Construction Tipper Dump Truck (16 CBM)",
    category: "haulage",
    brand: "BharatBenz",
    modelNumber: "2828C 6x4 Heavy Duty",
    year: 2023,
    tonnage: 28,
    horsepower: 280,
    fuelType: "Diesel",
    hourlyRate: 1900,
    dailyRate: 15500,
    monthlyRate: 380000,
    mobilizationBaseRatePerKm: 40,
    operatorIncluded: true,
    operatorDailyCharge: 1200,
    fuelIncluded: false,
    location: {
      lat: 12.9141,
      lng: 77.6109,
      city: "Bangalore South",
      district: "Bannerghatta & Jigani Quarry Corridor",
      state: "Karnataka",
      address: "Jigani Industrial Area Phase 1, Bengaluru",
    },
    rating: 4.84,
    reviewCount: 39,
    verified: true,
    rcNumber: "KA-51-TP-6601",
    insuranceValidUntil: "2027-02-28",
    fitnessValidUntil: "2028-12-19",
    ownerId: "owner-110",
    ownerName: "Karnataka Rock & Aggregate Transports",
    ownerPhone: "+91 98440 99812",
    operatorName: "Venkatesh Babu",
    operatorPhone: "+91 94490 11234",
    available: true,
    blockedDates: [],
    attachmentsAvailable: ["Hardox 450 Rock Body (16m³)", "Hydraulic Tipping Ram", "Automated Tarpaulin Cover"],
    specs: {
      bucketCapacityCbm: 16,
      liftingCapacityTons: 18,
    },
    liveGps: {
      lat: 12.92,
      lng: 77.625,
      speedKmH: 42,
      fuelLevelPct: 78,
      engineHours: 2150.0,
      batteryVoltage: 24.3,
      engineRpm: 1650,
      isOnline: true,
      immobilizerLocked: false,
      lastUpdated: "Just now",
    },
    images: [
      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1000&q=80",
    ],
    description: "Heavy 28-ton tipper with OM 926 BS-VI engine and high-tensile Hardox steel body. Specially engineered for quarry granite haulage, river sand transport, and metro muck clearing.",
  },
];

export const initialBookings: Booking[] = [
  {
    id: "BK-2026-8801",
    customerId: "cust-01",
    customerName: "Prajwal A. U. (Civil Contractor)",
    customerPhone: "+91 98765 43210",
    ownerId: "owner-101",
    ownerName: "Sri Manjunatha Earthmovers & Infra",
    equipmentId: "eq-01",
    equipmentName: "Tata Hitachi ZAXIS 220LC Hydraulic Excavator",
    equipmentImage: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=600&q=80",
    category: "earthmoving",
    locationAddress: "Brigade Tech Gardens, Brookefield, Whitefield, Bengaluru",
    locationCoords: { lat: 12.975, lng: 77.728 },
    startDate: "2026-08-28",
    endDate: "2026-08-30",
    durationDays: 3,
    requiresOperator: true,
    includeFuel: false,
    selectedAttachments: ["Heavy Duty Rock Breaker (150mm chisel)", "1.2m³ Heavy Bucket"],
    baseRental: 78000,
    mobilizationCost: 3900,
    operatorCost: 4500,
    fuelCost: 0,
    gstTax: 15552,
    securityDeposit: 25000,
    totalAmount: 126952,
    status: "IN_TRANSIT",
    paymentStatus: "ESCROW_HELD",
    paymentMethod: "UPI",
    liveEtaMinutes: 24,
    distanceRemainingKm: 14.8,
    currentTransitCoords: { lat: 12.9822, lng: 77.6105 },
    createdAt: "2026-08-27T18:30:00Z",
    hourlyLogs: [
      { date: "2026-08-28", startEngineHours: 1420.5, endEngineHours: 1428.5, verified: true },
    ],
  },
  {
    id: "BK-2026-8802",
    customerId: "cust-01",
    customerName: "Prajwal A. U.",
    customerPhone: "+91 98765 43210",
    ownerId: "owner-103",
    ownerName: "Krishi Mitra Agro Services",
    equipmentId: "eq-03",
    equipmentName: "John Deere W70 Grain Combine Harvester",
    equipmentImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80",
    category: "agricultural",
    locationAddress: "Srirangapatna Paddy Fields, Mandya District",
    locationCoords: { lat: 12.42, lng: 76.69 },
    startDate: "2026-09-02",
    endDate: "2026-09-03",
    durationDays: 2,
    requiresOperator: true,
    includeFuel: true,
    selectedAttachments: ["Paddy Cutter Bar (3.6m)"],
    baseRental: 38000,
    mobilizationCost: 2200,
    operatorCost: 3600,
    fuelCost: 5000,
    gstTax: 8784,
    securityDeposit: 15000,
    totalAmount: 72584,
    status: "ACCEPTED",
    paymentStatus: "ESCROW_HELD",
    paymentMethod: "NETBANKING",
    createdAt: "2026-08-26T14:15:00Z",
  },
  {
    id: "BK-2026-8790",
    customerId: "cust-02",
    customerName: "Ramesh Gowda (Farmer Union Head)",
    customerPhone: "+91 98450 77123",
    ownerId: "owner-102",
    ownerName: "Cauvery Farm & Agro Logistics",
    equipmentId: "eq-02",
    equipmentName: "JCB 3DX Plus EcoXcellence Backhoe Loader",
    equipmentImage: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80",
    category: "earthmoving",
    locationAddress: "Maddur Farm Canal Rd, Mandya",
    locationCoords: { lat: 12.58, lng: 77.04 },
    startDate: "2026-08-20",
    endDate: "2026-08-22",
    durationDays: 3,
    requiresOperator: true,
    includeFuel: false,
    selectedAttachments: ["6-in-1 Multi-purpose Front Shovel"],
    baseRental: 40500,
    mobilizationCost: 1800,
    operatorCost: 3600,
    fuelCost: 0,
    gstTax: 8262,
    securityDeposit: 15000,
    totalAmount: 69162,
    status: "COMPLETED",
    paymentStatus: "MILESTONE_RELEASED",
    paymentMethod: "UPI",
    createdAt: "2026-08-19T09:00:00Z",
    rating: 5,
    reviewText: "ಅತ್ಯುತ್ತಮ ಕೆಲಸ! ಆಪರೇಟರ್ ಶಿವಣ್ಣ ಅವರು ಕಾಲುವೆ ಅಗೆಯುವ ಕೆಲಸವನ್ನು ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಮುಗಿಸಿದರು. ಜೆಸಿಬಿ ಕಂಡಿಷನ್ ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು.",
  },
  {
    id: "BK-2026-8809",
    customerId: "cust-03",
    customerName: "Shree Builders & Developers",
    customerPhone: "+91 97311 00223",
    ownerId: "owner-105",
    ownerName: "BuildTech ReadyMix Fleet",
    equipmentId: "eq-05",
    equipmentName: "Ajax Fiori Argo 4000 Self-Loading Concrete Mixer",
    equipmentImage: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=600&q=80",
    category: "concrete",
    locationAddress: "Electronic City Phase 2, Bangalore",
    locationCoords: { lat: 12.839, lng: 77.677 },
    startDate: "2026-08-29",
    endDate: "2026-08-30",
    durationDays: 2,
    requiresOperator: true,
    includeFuel: false,
    selectedAttachments: ["Electronic Weigh Batching System"],
    baseRental: 45000,
    mobilizationCost: 3600,
    operatorCost: 3000,
    fuelCost: 0,
    gstTax: 9288,
    securityDeposit: 20000,
    totalAmount: 80888,
    status: "PENDING_APPROVAL",
    paymentStatus: "PENDING",
    paymentMethod: "CARD",
    createdAt: "2026-08-27T21:00:00Z",
  },
];

export const initialMaintenanceList: MaintenanceReminder[] = [
  {
    id: "mnt-01",
    equipmentId: "eq-01",
    equipmentName: "Tata Hitachi ZAXIS 220LC",
    category: "earthmoving",
    taskTitle: "Hydraulic Return Line Filter & Pilot Oil Replacement (1500h Service)",
    urgency: "HIGH",
    currentEngineHours: 1420.5,
    intervalHours: 1500,
    hoursRemaining: 79.5,
    estimatedCost: 14500,
    dueDate: "2026-09-08",
    status: "PENDING",
  },
  {
    id: "mnt-02",
    equipmentId: "eq-02",
    equipmentName: "JCB 3DX Plus Backhoe",
    category: "earthmoving",
    taskTitle: "Rear Axle Oil Change & Kingpin Greasing (1000h Service)",
    urgency: "CRITICAL",
    currentEngineHours: 890.2,
    intervalHours: 900,
    hoursRemaining: 9.8,
    estimatedCost: 6800,
    dueDate: "2026-08-30",
    status: "PENDING",
  },
  {
    id: "mnt-03",
    equipmentId: "eq-03",
    equipmentName: "John Deere W70 Harvester",
    category: "agricultural",
    taskTitle: "Threshing Drum Rasp Bar Inspection & V-Belt Tension Alignment",
    urgency: "NORMAL",
    currentEngineHours: 640.0,
    intervalHours: 800,
    hoursRemaining: 160.0,
    estimatedCost: 8200,
    dueDate: "2026-09-25",
    status: "SCHEDULED",
  },
  {
    id: "mnt-04",
    equipmentId: "eq-08",
    equipmentName: "PRD Super 650 Borewell Rig",
    category: "drilling",
    taskTitle: "Compressor Screw Element Oil & Air Filter Replacement",
    urgency: "NORMAL",
    currentEngineHours: 1210.0,
    intervalHours: 1500,
    hoursRemaining: 290.0,
    estimatedCost: 22000,
    dueDate: "2026-10-15",
    status: "PENDING",
  },
];

export const initialDisputes: DisputeCase[] = [
  {
    id: "DSP-401",
    bookingId: "BK-2026-8790",
    customerName: "Ramesh Gowda",
    ownerName: "Cauvery Farm & Agro Logistics",
    equipmentName: "JCB 3DX Plus",
    disputeType: "HOUR_METER_MISMATCH",
    claimAmount: 3200,
    description: "Customer claimed machine idle for 2 hours during rain. Owner's IoT logs showed engine was running at 1400 RPM performing sump dewatering.",
    filedAt: "2026-08-23T11:00:00Z",
    status: "RESOLVED",
    aiFraudScore: 12,
    aiVerdict: "FAVOR_OWNER_PARTIAL",
    aiJustification: "Telemetry GPS & RPM data proves hydraulic pump was actively engaged for dewatering waterlogged pit. Allowed 30 min standby concession.",
    aiRecommendedAction: "Waive ₹800 convenience charge, release balance escrow ₹2,400 to owner.",
    resolutionOutcome: "Settled with mutual customer & owner digital agreement.",
  },
  {
    id: "DSP-402",
    bookingId: "BK-2026-8801",
    customerName: "Prajwal A. U.",
    ownerName: "Sri Manjunatha Earthmovers",
    equipmentName: "Tata Hitachi ZAXIS 220LC",
    disputeType: "LATE_DELIVERY",
    claimAmount: 2000,
    description: "Low-bed trailer faced highway traffic jam near Hoskote toll gate, delayed by 1 hour 45 mins.",
    filedAt: "2026-08-28T06:30:00Z",
    status: "OPEN",
    aiFraudScore: 8,
    aiVerdict: "SPLIT_COMPROMISE",
    aiJustification: "GPS transit timestamp verifies NH48 police diversion. Unforeseen logistics impediment.",
    aiRecommendedAction: "Add 2 complimentary operational hours to ending shift without extra charge.",
  },
];

export const initialFraudFlags: FraudFlag[] = [
  {
    id: "FRD-101",
    type: "GEOFENCE_BREACH",
    severity: "MEDIUM",
    subject: "Tata Hitachi EX 200 (KA-01-EX-9921)",
    timestamp: "2026-08-27 16:42",
    details: "Machine moved 4.2 km outside authorized Whitefield project polygon during non-shift night hours.",
    status: "ACTION_TAKEN",
  },
  {
    id: "FRD-102",
    type: "FAKE_RC_DETECTION",
    severity: "CRITICAL",
    subject: "Owner Registration #8839 (CAT 320D)",
    timestamp: "2026-08-27 19:10",
    details: "Uploaded RC card image flagged: Font misalignment on Parivahan watermark and chassis hash mismatch.",
    status: "ACTIVE",
  },
  {
    id: "FRD-103",
    type: "UNUSUAL_RPM_SPIKE",
    severity: "LOW",
    subject: "Mahindra Novo 755 DI (KA-06-TR-8819)",
    timestamp: "2026-08-26 14:05",
    details: "Tractor engine exceeded recommended 2400 RPM continuous redline for 18 minutes.",
    status: "CLEARED",
  },
];
